apiVersion: v1
kind: Pod
metadata:
  labels:
    name: winpy
  name: winpy
spec:
  containers:
  - image: rajatchopra/winpyserver
    imagePullPolicy: IfNotPresent
    name: winpy
    ports:
    - containerPort: 80
      protocol: TCP
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  nodeSelector:
    beta.kubernetes.io/os: windows
  restartPolicy: Always
  securityContext:
    privileged: true
